<?xml version="1.0"?>

<robot name="limo_four_diff" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find limo_description)/urdf/limo_xacro.xacro" />
    <!-- <xacro:include filename="$(find limo_description)/urdf/limo_four_diff.gazebo" /> -->

    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.13" />
    <xacro:property name="base_y_size" value="0.12" />
    <xacro:property name="base_z_size" value="0.1" />
  
    <xacro:property name="wheelbase" value="0.2"/>
    <xacro:property name="track" value="0.13"/>
    <xacro:property name="wheel_vertical_offset" value="-0.10" />
    <xacro:property name="base_mass" value="2.1557"/>

    <xacro:property name="wheel_length" value="0.045" />
    <xacro:property name="wheel_radius" value="0.045" />
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.15" rpy="0 0 0"/>
  </joint>
    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 -0.15" rpy="0 0 1.57" />
            <geometry>
                <mesh filename="file://$(find limo_description)/meshes/limo_base.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <!--origin xyz="0 0 -0.15" rpy="0 0 1.57" /-->
            <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
              <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
          </geometry>
        </collision>
    </link>

    <link name="inertial_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" />
            <mass value="${base_mass}" />
            <inertia ixx="0.24" ixy="0" ixz="0" 
                     iyy="0.96" iyz="0" 
                     izz="0.96" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <!-- <xacro:limo_laser parent_prefix="base_link" frame_prefix="laser">
        <origin xyz="0.103 0 -0.034" rpy="0 0 0"/>
    </xacro:limo_laser>

    <xacro:limo_depth_camera parent_prefix="base_link" frame_prefix="depth_camera">
        <origin xyz="0.084 0 0.03" rpy="0 0 0"/>
    </xacro:limo_depth_camera>
    
    <xacro:limo_imu parent_prefix="base_link" frame_prefix="imu">
        <origin xyz="0.0 0 -0.1" rpy="0 0 0"/>
    </xacro:limo_imu> -->

    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="front_left" reflect="1">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0  0" />
    </xacro:limo_wheel>

    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="front_right" reflect="-1">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
    </xacro:limo_wheel>

    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="rear_left" reflect="1">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:limo_wheel>

    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="rear_right" reflect="-1">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
    </xacro:limo_wheel>

    <link name='laser_link'>
        <pose>0 0 0 0 0 0</pose>
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0.0 0 0" rpy="0 0 0"/>
            <inertia
                ixx="1e-6" ixy="0" ixz="0"
                iyy="1e-6" iyz="0"
                izz="1e-6"
            />
        </inertial>
        <visual name='laser_visual'>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.02" length="0.01"/>
            </geometry>
            <material name='laser_material'>
                <ambient>0.1 0.1 0.1 1</ambient>
                <diffuse>0.1 0.1 0.2 1</diffuse>
                <specular>0 0 0 0</specular>
                <emissive>0 0 0 1</emissive>
            </material>
        </visual>
        <collision name='laser_collision'>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.032" length="0.016"/>
            </geometry>
        </collision>
    </link>
    <joint type="fixed" name="laser_joint">
        <origin xyz='0 0 0' rpy='0 -0 0'/>
        <child link="laser_link"/>
        <parent link="base_link"/>
    </joint>
    <gazebo reference="laser_link">
      <turnGravityOff>false</turnGravityOff>
      <sensor type="gpu_ray" name="laser">
        <update_rate>40</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>720</samples>
              <resolution>1</resolution>
              <min_angle>-2</min_angle>
              <max_angle>2</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.04</min>
            <max>30.0</max>
            <resolution>0.01</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
       <plugin name="gazebo_ros_planar_lidar" filename="libgazebo_ros_gpu_laser.so">
          <topicName>scan</topicName>
          <frameName>laser_link</frameName>
          <robotNamespace>/</robotNamespace>
        </plugin>
      </sensor>
    </gazebo>

     <link name='camera_link'>
            <pose>0 0 0 0 0 0</pose>
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0.0 0 0" rpy="0 0 0"/>
                <inertia
                    ixx="1e-6" ixy="0" ixz="0"
                    iyy="1e-6" iyz="0"
                    izz="1e-6"
                />
            </inertial>
            <visual name='depth_camera_visual'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.06 0.015"/>
                </geometry>
                <material name='depth_camera_material'>
                    <ambient>0.1 0.1 0.1 1</ambient>
                    <diffuse>0.1 0.1 0.2 1</diffuse>
                    <specular>0 0 0 0</specular>
                    <emissive>0 0 0 1</emissive>
                </material>
            </visual>
            <collision name='depth_camera_collision'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.06 0.015"/>
                </geometry>
            </collision>
            <sensor name="thermal_camera_8bit" type="thermal">
            <camera>
                <horizontal_fov>1.047</horizontal_fov>
                <image>
                <width>320</width>
                <height>240</height>
                <format>L8</format>
                </image>
                <clip>
                <near>0.1</near>
                <far>100</far>
                </clip>
            </camera>
            <always_on>1</always_on>
            <update_rate>30</update_rate>
            <visualize>true</visualize>
            <topic>thermal_camera_8bit/image</topic>
            <plugin
                filename="ignition-gazebo-thermal-sensor-system"
                name="ignition::gazebo::systems::ThermalSensor">
                <min_temp>253.15</min_temp>
                <max_temp>673.15</max_temp>
                <resolution>3.0</resolution>
            </plugin>
            </sensor>
        </link>
    
        <joint type="fixed" name="depth_camera_joint">
            <origin xyz='0 0 0.1' rpy='0 -0 0'/>
            <child link="camera_link"/>
            <parent link="base_link"/>
        </joint>
        <link name="depth_link"></link>

        <joint name="camera_to_camera_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2} "/>
            <parent link="camera_link"/>
            <child link="depth_link"/>
          </joint>

        <gazebo reference="camera_link">
        <sensor type="depth" name="camera">
            <always_on>true</always_on>
            <update_rate>30</update_rate>
            <camera>
            <horizontal_fov>${60.0*M_PI/180.0}</horizontal_fov>
            <image>
                <format>R8G8B8</format>
                <width>320</width>
                <height>240</height>
            </image>
            <clip>
                <near>0.05</near>
                <far>0.8</far>
            </clip>
            </camera>
            <plugin name="rgbd_camera_controller" filename="libgazebo_ros_depth_camera.so">
            <cameraName>camera</cameraName>
            <alwaysOn>true</alwaysOn>
            <updateRate>30</updateRate>
            <imageTopicName>rgb/image_raw</imageTopicName>
            <depthImageTopicName>depth/image_raw</depthImageTopicName>
            <pointCloudTopicName>depth/points</pointCloudTopicName>
            <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
            <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
            <frameName>camera_frame_optical</frameName>
            <baseline>0.1</baseline>
            <distortion_k1>0.0</distortion_k1>
            <distortion_k2>0.0</distortion_k2>
            <distortion_k3>0.0</distortion_k3>
            <distortion_t1>0.0</distortion_t1>
            <distortion_t2>0.0</distortion_t2>
            <pointCloudCutoff>0.6</pointCloudCutoff>
            <pointCloudCutoffMax>8</pointCloudCutoffMax>
            <robotNamespace>/</robotNamespace>
            </plugin>
        </sensor>
        </gazebo>
</robot>
